# Generated by Django 4.2.5 on 2023-10-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
                ('nacimiento', models.DateField()),
                ('u_consulta', models.DateField()),
                ('medico', models.CharField(max_length=60)),
            ],
        ),
    ]
