# Generated by Django 4.2.5 on 2023-10-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_remove_pacientes_id_alter_pacientes_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chosen_avatar',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
