# Generated by Django 4.2.5 on 2023-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0006_userprofile_numero_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chosen_avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
