# Generated by Django 4.2.5 on 2023-10-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0010_rename_usermed_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
