# Generated by Django 4.2.5 on 2023-10-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacientesInternados',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
                ('nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('medico', models.CharField(max_length=60)),
            ],
        ),
    ]
