# Generated by Django 4.2.5 on 2023-10-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0012_pacientesinternados'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientesinternados',
            name='sala_asignada',
            field=models.CharField(default='1A', max_length=60),
        ),
    ]
