# Generated by Django 4.2.5 on 2023-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0013_pacientesinternados_sala_asignada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('localidad', models.CharField(max_length=60)),
            ],
        ),
    ]
