# Generated by Django 4.2.5 on 2023-10-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalapp', '0014_hospitales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('rama', models.CharField(choices=[('Traumatologo', 'Traumatologo'), ('Oftalmologo', 'Oftalmologo'), ('Enfermero', 'Enfermero'), ('Cirujano', 'Cirujano')], max_length=20)),
                ('numero_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapp.hospitales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
