# Generated by Django 4.2.5 on 2023-10-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0015_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalapp.hospitales'),
        ),
    ]
