# Generated by Django 4.2.5 on 2023-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0016_alter_medicos_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='numero_matricula',
            field=models.AutoField(default=123456, primary_key=True, serialize=False),
        ),
    ]
